#!/bin/bash

file_source=${1}
folder_source=${2}
folder_target=${3}
push=${4}

source_repo="source"
target_repos="target destination"
source_branch="B_source"
target_branch="B_target"

cd ${source_repo}
git checkout ${source_branch}
git log --pretty=email --patch-with-stat --reverse --full-index --binary -m --first-parent \
    -- ${folder_source}/${file_source} >> ../copy.patch
cd ..
sed -i "s/${folder_source}\//${folder_target}\//g" copy.patch

for target_repo in ${target_repos}
    cd ${target_repo}
    git checkout ${target_branch}
    git am --committer-date-is-author-date < ../copy.patch
    #git mv ${file_source} ${file_target}
    #git commit -m "copy file ${file_source} from ${source_branch} branch to file ${file_target} in ${target_branch} branch"
    [ "${push}" == "push" ] && git push
    cd ..
done
